import * as vscode from 'vscode';

/**
 * Payload emitted by the AMD form when the user clicks "Generate".
 * Field names mirror pharmpy's run_amd() kwargs. Only modality-relevant fields
 * are read when building the R script, so extra keys are harmless.
 */
interface AmdConfig {
    modeltype: string;                     // basic_pk | pkpd | tmdd | drug_metabolite
    input: string;
    administration: string;                // iv | oral | iv+oral
    strategy: string;                      // default | reevaluation | SIR | SRI | RSI
    retriesStrategy: string;               // skip | all_final | final
    parameterUncertaintyMethod: string;    // SANDWICH | SMAT | RMAT | EFIM | none
    searchSpace: string;
    seed?: number;
    estTool: string;                       // nonmem (default) | nlmixr2 | generic
    clInit?: number;
    vcInit?: number;
    matInit?: number;
    bInit?: number;
    emaxInit?: number;
    ec50Init?: number;
    metInit?: number;
    dvTypes?: string;                      // "drug:1,target:2,complex:3" -> R list(...)
}

const MODELTYPE_LABELS: Record<string, string> = {
    basic_pk: 'PK (basic_pk)',
    pkpd: 'PK-PD (pkpd)',
    tmdd: 'TMDD (tmdd)',
    drug_metabolite: 'Drug Metabolite (drug_metabolite)'
};

function escapeR(str: string): string {
    return str.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function parseDvTypes(raw: string): string | undefined {
    // Accept "drug:1, target:2, complex:3" and emit an R list("drug" = 1, ...) fragment.
    const pairs = raw.split(',').map(p => p.trim()).filter(Boolean);
    if (pairs.length === 0) { return undefined; }
    const parts: string[] = [];
    for (const pair of pairs) {
        const [k, v] = pair.split(':').map(s => s?.trim());
        if (!k || !v || isNaN(Number(v))) { return undefined; }
        parts.push(`"${k}" = ${Number(v)}`);
    }
    return `list(${parts.join(', ')})`;
}

/**
 * Build an editable R script that mirrors the form state as a run_amd() call.
 * We intentionally omit optional args that are on their default so the emitted
 * script stays readable and doesn't hardcode pharmr's shifting defaults.
 */
function generateRScript(cfg: AmdConfig): string {
    const lines: string[] = [];
    const label = MODELTYPE_LABELS[cfg.modeltype] ?? cfg.modeltype;
    lines.push('# Auto-generated by nmbench — AMD Script Generator');
    lines.push(`# Modality: ${label}`);
    lines.push(`# Estimation tool: ${cfg.estTool || 'nonmem'} (pharmpy default)`);
    lines.push('# Review each argument before running. Some pharmr signatures may differ');
    lines.push('# from pharmpy Python — cross-check with ?pharmr::run_amd if in doubt.');
    lines.push('');
    lines.push('library(pharmr)');
    lines.push('');

    const args: string[] = [];
    args.push(`  input = "${escapeR(cfg.input || 'path/to/data.csv')}"`);
    args.push(`  modeltype = "${cfg.modeltype}"`);
    args.push(`  administration = "${cfg.administration}"`);

    if (cfg.clInit !== undefined) { args.push(`  cl_init = ${cfg.clInit}`); }
    if (cfg.vcInit !== undefined) { args.push(`  vc_init = ${cfg.vcInit}`); }
    if (cfg.administration === 'oral' || cfg.administration === 'iv+oral') {
        if (cfg.matInit !== undefined) { args.push(`  mat_init = ${cfg.matInit}`); }
    }

    if (cfg.modeltype === 'pkpd') {
        if (cfg.bInit !== undefined) { args.push(`  b_init = ${cfg.bInit}`); }
        if (cfg.emaxInit !== undefined) { args.push(`  emax_init = ${cfg.emaxInit}`); }
        if (cfg.ec50Init !== undefined) { args.push(`  ec50_init = ${cfg.ec50Init}`); }
        if (cfg.metInit !== undefined) { args.push(`  met_init = ${cfg.metInit}`); }
    }
    if (cfg.modeltype === 'tmdd' && cfg.dvTypes) {
        const rList = parseDvTypes(cfg.dvTypes);
        if (rList) { args.push(`  dv_types = ${rList}`); }
    }

    if (cfg.searchSpace && cfg.searchSpace.trim()) {
        args.push(`  search_space = "${escapeR(cfg.searchSpace.trim())}"`);
    }
    if (cfg.strategy && cfg.strategy !== 'default') {
        args.push(`  strategy = "${cfg.strategy}"`);
    }
    if (cfg.retriesStrategy && cfg.retriesStrategy !== 'skip') {
        args.push(`  retries_strategy = "${cfg.retriesStrategy}"`);
    }
    if (cfg.parameterUncertaintyMethod && cfg.parameterUncertaintyMethod !== 'none') {
        args.push(`  parameter_uncertainty_method = "${cfg.parameterUncertaintyMethod}"`);
    }
    if (cfg.estTool && cfg.estTool !== 'nonmem') {
        args.push(`  esttool = "${cfg.estTool}"`);
    }
    if (cfg.seed !== undefined) { args.push(`  seed = ${cfg.seed}`); }

    lines.push('result <- run_amd(');
    lines.push(args.join(',\n'));
    lines.push(')');
    lines.push('');
    lines.push('# Summary tables');
    lines.push('print(result$summary_tool)');
    lines.push('print(result$summary_models)');
    lines.push('print(result$summary_errors)');
    lines.push('');

    return lines.join('\n');
}

export class AmdViewProvider implements vscode.WebviewViewProvider {
    public static readonly viewType = 'amdView';
    private _view?: vscode.WebviewView;
    private _previewDoc?: vscode.TextDocument;
    private _previewContent?: string;

    constructor(private readonly context: vscode.ExtensionContext) {}

    resolveWebviewView(view: vscode.WebviewView): void {
        this._view = view;
        view.webview.options = { enableScripts: true };
        view.webview.html = this.getHtml();

        view.webview.onDidReceiveMessage(async (msg) => {
            if (msg.command === 'browseInput') {
                const picked = await vscode.window.showOpenDialog({
                    canSelectFiles: true,
                    canSelectFolders: false,
                    canSelectMany: false,
                    openLabel: 'Select data / model file',
                    filters: {
                        'Datasets & models': ['csv', 'tsv', 'txt', 'mod', 'ctl', 'lst'],
                        'All files': ['*']
                    }
                });
                if (picked && picked[0]) {
                    view.webview.postMessage({ command: 'inputPicked', path: picked[0].fsPath });
                }
                return;
            }

            if (msg.command === 'generate') {
                const script = generateRScript(msg.config as AmdConfig);
                await this.openPreviewDoc(script);
                return;
            }
        });
    }

    /**
     * Open the generated script as an untitled R document. If a previous tab is
     * still open AND still holds our last-emitted content (i.e. the user hasn't
     * edited it), we replace its contents in place so successive Generate clicks
     * don't spam new tabs. If the user has edited that tab we create a fresh one
     * so their edits are preserved. Cmd/Ctrl+S in the editor then handles saving
     * the untitled document wherever the user wants.
     */
    private async openPreviewDoc(script: string): Promise<void> {
        const canReuse = !!this._previewDoc
            && !this._previewDoc.isClosed
            && this._previewDoc.getText() === this._previewContent;
        if (canReuse && this._previewDoc) {
            const edit = new vscode.WorkspaceEdit();
            edit.replace(this._previewDoc.uri, new vscode.Range(0, 0, this._previewDoc.lineCount, 0), script);
            await vscode.workspace.applyEdit(edit);
            this._previewContent = script;
            await vscode.window.showTextDocument(this._previewDoc, { viewColumn: vscode.ViewColumn.One, preview: false });
            return;
        }
        const doc = await vscode.workspace.openTextDocument({ language: 'r', content: script });
        this._previewDoc = doc;
        this._previewContent = script;
        await vscode.window.showTextDocument(doc, { viewColumn: vscode.ViewColumn.One, preview: false });
    }

    private getHtml(): string {
        // The form covers all four modalities up-front; modality-specific sections are toggled by JS.
        // Only PK is treated as "validated" today — the others are flagged as beta so users know to
        // review the emitted script before running.
        return /* html */`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: var(--vscode-font-family);
            font-size: var(--vscode-font-size);
            color: var(--vscode-foreground);
            padding: 8px 10px;
            margin: 0;
        }
        h3 {
            margin: 14px 0 6px;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.6px;
            color: var(--vscode-charts-blue, var(--vscode-textLink-foreground));
            padding: 3px 0 4px 10px;
            border-left: 3px solid var(--vscode-charts-blue, var(--vscode-textLink-foreground));
        }
        label {
            display: block;
            margin: 6px 0 2px;
            font-size: 12px;
        }
        input[type="text"], input[type="number"], select, textarea {
            width: 100%;
            box-sizing: border-box;
            background: var(--vscode-input-background);
            color: var(--vscode-input-foreground);
            border: 1px solid var(--vscode-input-border, transparent);
            padding: 3px 5px;
            font-family: var(--vscode-font-family);
            font-size: 12px;
        }
        textarea { min-height: 44px; font-family: var(--vscode-editor-font-family); }
        .row { display: flex; gap: 6px; align-items: end; }
        .row > * { flex: 1; }
        button {
            background: var(--vscode-button-background);
            color: var(--vscode-button-foreground);
            border: none;
            padding: 5px 10px;
            cursor: pointer;
            font-size: 12px;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            line-height: 1.2;
        }
        button:hover { background: var(--vscode-button-hoverBackground); }
        button.secondary {
            background: transparent;
            color: var(--vscode-charts-blue, var(--vscode-textLink-foreground));
            border: 1px solid var(--vscode-charts-blue, var(--vscode-textLink-foreground));
        }
        button.secondary:hover {
            background: rgba(100, 170, 255, 0.1);
        }
        button.primary {
            background: rgba(71, 212, 90, 0.1);
            color: var(--vscode-charts-green, var(--vscode-textLink-foreground));
            border: 1px solid var(--vscode-charts-green, var(--vscode-textLink-foreground));
        }
        button.primary:hover {
            background: rgba(71, 212, 90, 0.2);
        }
        .modality-section { display: none; }
        .modality-section.active {
            display: block;
            padding: 6px 10px 8px;
            background: rgba(160, 120, 220, 0.06);
            border-left: 2px solid var(--vscode-charts-purple, var(--vscode-textLink-foreground));
            margin: 4px 0 8px;
            border-radius: 0 4px 4px 0;
        }
        .beta-badge {
            display: inline-block;
            font-size: 10px;
            background: var(--vscode-charts-yellow, #f2c94c);
            color: var(--vscode-editor-background, #000);
            padding: 1px 5px;
            border-radius: 3px;
            margin-left: 6px;
            vertical-align: middle;
        }
        .hint {
            font-size: 11px;
            color: var(--vscode-descriptionForeground);
            margin-top: 2px;
        }
        .actions {
            display: flex;
            gap: 6px;
            margin-top: 10px;
            padding-top: 8px;
            border-top: 1px solid var(--vscode-panel-border);
        }
        .status {
            font-size: 11px;
            color: var(--vscode-descriptionForeground);
            margin-top: 6px;
            min-height: 14px;
        }
    </style>
</head>
<body>
    <h3>Modality</h3>
    <select id="modeltype">
        <option value="basic_pk">PK — basic_pk</option>
        <option value="pkpd">PK-PD — pkpd (beta)</option>
        <option value="tmdd">TMDD — tmdd (beta)</option>
        <option value="drug_metabolite">Drug Metabolite — drug_metabolite (beta)</option>
    </select>
    <div id="beta-note" class="hint" style="display:none;">
        Beta modality — cross-check emitted script against <code>?pharmr::run_amd</code> before running.
    </div>

    <h3>Input</h3>
    <div class="row">
        <input type="text" id="input" placeholder="Path to dataset (or start model for PK-PD)">
        <button class="secondary" id="browse-input" style="flex:0 0 auto;">Browse…</button>
    </div>

    <h3>Common</h3>
    <div class="row">
        <div>
            <label for="administration">Administration</label>
            <select id="administration">
                <option value="iv">iv</option>
                <option value="oral" selected>oral</option>
                <option value="iv+oral">iv+oral</option>
            </select>
        </div>
        <div>
            <label for="estTool">Estimation tool</label>
            <select id="estTool">
                <option value="nonmem" selected>nonmem (default)</option>
                <option value="nlmixr2">nlmixr2</option>
                <option value="generic">generic</option>
            </select>
        </div>
    </div>

    <h3>Initial estimates</h3>
    <div class="row">
        <div>
            <label for="clInit">cl_init</label>
            <input type="number" id="clInit" step="any" placeholder="e.g. 2.0">
        </div>
        <div>
            <label for="vcInit">vc_init</label>
            <input type="number" id="vcInit" step="any" placeholder="e.g. 5.0">
        </div>
        <div id="matInitCell">
            <label for="matInit">mat_init <span class="hint">(oral)</span></label>
            <input type="number" id="matInit" step="any" placeholder="e.g. 3.0">
        </div>
    </div>

    <div id="section-pkpd" class="modality-section">
        <h3>PK-PD initial estimates <span class="beta-badge">beta</span></h3>
        <div class="row">
            <div>
                <label for="bInit">b_init</label>
                <input type="number" id="bInit" step="any">
            </div>
            <div>
                <label for="emaxInit">emax_init</label>
                <input type="number" id="emaxInit" step="any">
            </div>
        </div>
        <div class="row">
            <div>
                <label for="ec50Init">ec50_init</label>
                <input type="number" id="ec50Init" step="any">
            </div>
            <div>
                <label for="metInit">met_init</label>
                <input type="number" id="metInit" step="any">
            </div>
        </div>
        <div class="hint">Input should be a fully-built PK model (not a raw dataset). Dataset must have DVID = 1 (PK) / 2 (PD).</div>
    </div>

    <div id="section-tmdd" class="modality-section">
        <h3>TMDD <span class="beta-badge">beta</span></h3>
        <label for="dvTypes">dv_types</label>
        <input type="text" id="dvTypes" placeholder="drug:1, target:2, complex:3">
        <div class="hint">Comma-separated key:value pairs mapping DV components to DVID integers.</div>
    </div>

    <div id="section-drug_metabolite" class="modality-section">
        <h3>Drug Metabolite <span class="beta-badge">beta</span></h3>
        <div class="hint">Dataset must have DVID = 1 (parent) / 2 (metabolite). Suggested search space:
            <code>METABOLITE([BASIC,PSC]);PERIPHERALS(0..1,MET)</code>.
        </div>
    </div>

    <h3>Advanced</h3>
    <div class="row">
        <div>
            <label for="strategy">strategy</label>
            <select id="strategy">
                <option value="default" selected>default</option>
                <option value="reevaluation">reevaluation</option>
                <option value="SIR">SIR</option>
                <option value="SRI">SRI</option>
                <option value="RSI">RSI</option>
            </select>
        </div>
        <div>
            <label for="retriesStrategy">retries_strategy</label>
            <select id="retriesStrategy">
                <option value="skip" selected>skip</option>
                <option value="all_final">all_final</option>
                <option value="final">final</option>
            </select>
        </div>
    </div>
    <div class="row">
        <div>
            <label for="parameterUncertaintyMethod">parameter_uncertainty_method</label>
            <select id="parameterUncertaintyMethod">
                <option value="none" selected>(none)</option>
                <option value="SANDWICH">SANDWICH</option>
                <option value="SMAT">SMAT</option>
                <option value="RMAT">RMAT</option>
                <option value="EFIM">EFIM</option>
            </select>
        </div>
        <div>
            <label for="seed">seed</label>
            <input type="number" id="seed" step="1" placeholder="e.g. 1234">
        </div>
    </div>
    <label for="searchSpace">search_space (MFL)</label>
    <textarea id="searchSpace" placeholder="Leave blank to use pharmpy's default"></textarea>

    <div class="actions">
        <button class="primary" id="generate">Generate Code</button>
    </div>

    <script>
        const vscode = acquireVsCodeApi();

        const modeltypeEl = document.getElementById('modeltype');
        const betaNote = document.getElementById('beta-note');
        const administrationEl = document.getElementById('administration');
        const matCell = document.getElementById('matInitCell');

        function refreshModality() {
            const value = modeltypeEl.value;
            for (const key of ['pkpd', 'tmdd', 'drug_metabolite']) {
                const section = document.getElementById('section-' + key);
                if (section) { section.classList.toggle('active', value === key); }
            }
            betaNote.style.display = value === 'basic_pk' ? 'none' : 'block';
        }
        function refreshAdministration() {
            const isOral = administrationEl.value === 'oral' || administrationEl.value === 'iv+oral';
            matCell.style.opacity = isOral ? '1' : '0.4';
        }
        modeltypeEl.addEventListener('change', refreshModality);
        administrationEl.addEventListener('change', refreshAdministration);
        refreshModality();
        refreshAdministration();

        function collect() {
            const num = (id) => {
                const raw = document.getElementById(id).value;
                if (raw === '' || raw === null || raw === undefined) { return undefined; }
                const n = Number(raw);
                return Number.isFinite(n) ? n : undefined;
            };
            const str = (id) => document.getElementById(id).value;
            return {
                modeltype: str('modeltype'),
                input: str('input'),
                administration: str('administration'),
                strategy: str('strategy'),
                retriesStrategy: str('retriesStrategy'),
                parameterUncertaintyMethod: str('parameterUncertaintyMethod'),
                searchSpace: str('searchSpace'),
                estTool: str('estTool'),
                seed: num('seed'),
                clInit: num('clInit'),
                vcInit: num('vcInit'),
                matInit: num('matInit'),
                bInit: num('bInit'),
                emaxInit: num('emaxInit'),
                ec50Init: num('ec50Init'),
                metInit: num('metInit'),
                dvTypes: str('dvTypes')
            };
        }

        document.getElementById('browse-input').addEventListener('click', () => {
            vscode.postMessage({ command: 'browseInput' });
        });
        document.getElementById('generate').addEventListener('click', () => {
            vscode.postMessage({ command: 'generate', config: collect() });
        });

        window.addEventListener('message', (event) => {
            const msg = event.data;
            if (msg.command === 'inputPicked') {
                document.getElementById('input').value = msg.path;
            }
        });
    </script>
</body>
</html>`;
    }
}
