import * as vscode from 'vscode';

/**
 * Snapshot of the Model Builder form, sent from the webview when the user clicks
 * Preview or Generate. Field names loosely mirror pharmpy Python kwargs where a
 * 1:1 mapping is available; ambiguous ones are marked in the emitted R script.
 */
interface CovariateEffect {
    parameter: string;
    covariate: string;
    effect: string;
    operation: string;
}

interface ModelBuilderConfig {
    baseKind: string;               // fromDataset | fromModel
    dataset: string;                // when fromDataset
    modelFile: string;              // when fromModel
    modelName: string;
    datatype: string;               // nonmem | nlmixr | ...
    administration: string;         // iv | oral | iv+oral
    absorption: string;             // FO | ZO | SEQ-ZO-FO | none
    transits: number;               // 0 = disabled
    lagTime: boolean;
    elimination: string;            // FO | ZO | MM | MIX-FO-MM
    peripherals: number;            // 0..n
    iivParameters: string[];        // e.g. ["CL","V"]
    iivType: string;                // exp | prop | add
    errorModel: string;             // none | additive | proportional | combined
    dv: string;                     // DV column name (optional)
    covariates: CovariateEffect[];
    outputFormat: string;           // nonmem | nlmixr2 | ...
    outputModelFile: string;        // filename to write via write_model
}

function escapeR(str: string): string {
    return str.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function rStringVec(items: string[]): string {
    if (items.length === 0) { return 'character(0)'; }
    return 'c(' + items.map(s => `"${escapeR(s)}"`).join(', ') + ')';
}

/**
 * Build an editable R script mirroring the form state. Emitted as direct
 * `set_*`/`add_*` calls (rather than MFL) because pharmr's mirrored names are
 * more readable for users who will hand-edit before running.
 */
function generateRScript(cfg: ModelBuilderConfig): string {
    const lines: string[] = [];
    lines.push('# Auto-generated by nmbench — Model Builder');
    lines.push(`# Output target: ${cfg.outputFormat}`);
    lines.push('# pharmr mirrors pharmpy.modeling naming (snake_case). If a call below fails,');
    lines.push('# check `ls("package:pharmr")` for the exact function name.');
    lines.push('');
    lines.push('library(pharmr)');
    lines.push('');

    if (cfg.baseKind === 'fromModel' && cfg.modelFile) {
        lines.push(`model <- read_model("${escapeR(cfg.modelFile)}")`);
    } else {
        const args: string[] = [];
        if (cfg.dataset) { args.push(`  dataset = "${escapeR(cfg.dataset)}"`); }
        if (cfg.administration) { args.push(`  administration = "${cfg.administration}"`); }
        lines.push('model <- create_basic_pk_model(');
        lines.push(args.join(',\n'));
        lines.push(')');
    }
    if (cfg.modelName && cfg.modelName.trim()) {
        lines.push(`model <- set_name(model, "${escapeR(cfg.modelName.trim())}")`);
    }
    lines.push('');

    lines.push('# --- Structural features ---');
    switch (cfg.absorption) {
        case 'FO': lines.push('model <- set_first_order_absorption(model)'); break;
        case 'ZO': lines.push('model <- set_zero_order_absorption(model)'); break;
        case 'SEQ-ZO-FO': lines.push('model <- set_seq_zo_fo_absorption(model)'); break;
    }
    if (cfg.transits > 0) {
        // Second arg is the depot flag; leaving TRUE mirrors pharmpy's default.
        lines.push(`model <- set_transit_compartments(model, ${cfg.transits}, keep_depot = TRUE)`);
    }
    if (cfg.lagTime) {
        lines.push('model <- add_lag_time(model)');
    }
    switch (cfg.elimination) {
        case 'FO': lines.push('model <- set_first_order_elimination(model)'); break;
        case 'ZO': lines.push('model <- set_zero_order_elimination(model)'); break;
        case 'MM': lines.push('model <- set_michaelis_menten_elimination(model)'); break;
        case 'MIX-FO-MM': lines.push('model <- set_mixed_mm_fo_elimination(model)'); break;
    }
    for (let i = 0; i < cfg.peripherals; i++) {
        lines.push('model <- add_peripheral_compartment(model)');
    }
    lines.push('');

    if (cfg.iivParameters.length > 0) {
        lines.push('# --- Between-subject variability ---');
        const params = rStringVec(cfg.iivParameters);
        lines.push(`model <- add_iiv(model, ${params}, "${cfg.iivType}")`);
        lines.push('');
    }

    if (cfg.errorModel && cfg.errorModel !== 'none') {
        lines.push('# --- Residual error model ---');
        const dvArg = cfg.dv && cfg.dv.trim() ? `, dv = "${escapeR(cfg.dv.trim())}"` : '';
        switch (cfg.errorModel) {
            case 'additive':     lines.push(`model <- set_additive_error_model(model${dvArg})`); break;
            case 'proportional': lines.push(`model <- set_proportional_error_model(model${dvArg})`); break;
            case 'combined':     lines.push(`model <- set_combined_error_model(model${dvArg})`); break;
        }
        lines.push('');
    }

    if (cfg.covariates.length > 0) {
        lines.push('# --- Covariate effects ---');
        for (const c of cfg.covariates) {
            if (!c.parameter || !c.covariate || !c.effect) { continue; }
            const op = c.operation || '*';
            lines.push(`model <- add_covariate_effect(model, "${escapeR(c.parameter)}", "${escapeR(c.covariate)}", "${escapeR(c.effect)}", "${escapeR(op)}")`);
        }
        lines.push('');
    }

    lines.push('# --- Convert & write ---');
    if (cfg.outputFormat && cfg.outputFormat !== 'none') {
        lines.push(`model <- convert_model(model, to_format = "${cfg.outputFormat}")`);
    }
    if (cfg.outputModelFile && cfg.outputModelFile.trim()) {
        // write_model is a candidate name — pharmpy exposes it in Python; verify pharmr export.
        lines.push(`# If write_model() is unavailable in your pharmr version, use writeLines(as.character(model), "...")`);
        lines.push(`write_model(model, path = "${escapeR(cfg.outputModelFile.trim())}", force = TRUE)`);
    }
    lines.push('');

    return lines.join('\n');
}

export class ModelBuilderViewProvider implements vscode.WebviewViewProvider {
    public static readonly viewType = 'modelBuilderView';
    private _view?: vscode.WebviewView;
    private _previewDoc?: vscode.TextDocument;
    private _previewContent?: string;

    constructor(private readonly context: vscode.ExtensionContext) {}

    resolveWebviewView(view: vscode.WebviewView): void {
        this._view = view;
        view.webview.options = { enableScripts: true };
        view.webview.html = this.getHtml();

        view.webview.onDidReceiveMessage(async (msg) => {
            if (msg.command === 'browseDataset' || msg.command === 'browseModel') {
                const isModel = msg.command === 'browseModel';
                const picked = await vscode.window.showOpenDialog({
                    canSelectFiles: true,
                    canSelectFolders: false,
                    canSelectMany: false,
                    openLabel: isModel ? 'Select model file' : 'Select dataset',
                    filters: isModel
                        ? { 'Model files': ['mod', 'ctl', 'lst'], 'All files': ['*'] }
                        : { 'Datasets': ['csv', 'tsv', 'txt'], 'All files': ['*'] }
                });
                if (picked && picked[0]) {
                    view.webview.postMessage({
                        command: isModel ? 'modelPicked' : 'datasetPicked',
                        path: picked[0].fsPath
                    });
                }
                return;
            }

            if (msg.command === 'generate') {
                const script = generateRScript(msg.config as ModelBuilderConfig);
                await this.openPreviewDoc(script);
                return;
            }
        });
    }

    /**
     * Open the generated script as an untitled R document. Reuses the previous
     * tab when its content is still what we last emitted so successive Generate
     * clicks don't spam tabs; if the user has edited that tab a fresh one is
     * created to preserve their edits. Cmd/Ctrl+S in the editor handles saving.
     */
    private async openPreviewDoc(script: string): Promise<void> {
        const canReuse = !!this._previewDoc
            && !this._previewDoc.isClosed
            && this._previewDoc.getText() === this._previewContent;
        if (canReuse && this._previewDoc) {
            const edit = new vscode.WorkspaceEdit();
            edit.replace(this._previewDoc.uri, new vscode.Range(0, 0, this._previewDoc.lineCount, 0), script);
            await vscode.workspace.applyEdit(edit);
            this._previewContent = script;
            await vscode.window.showTextDocument(this._previewDoc, { viewColumn: vscode.ViewColumn.One, preview: false });
            return;
        }
        const doc = await vscode.workspace.openTextDocument({ language: 'r', content: script });
        this._previewDoc = doc;
        this._previewContent = script;
        await vscode.window.showTextDocument(doc, { viewColumn: vscode.ViewColumn.One, preview: false });
    }

    private getHtml(): string {
        return /* html */`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: var(--vscode-font-family);
            font-size: var(--vscode-font-size);
            color: var(--vscode-foreground);
            padding: 8px 10px;
            margin: 0;
        }
        h3 {
            margin: 14px 0 6px;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.6px;
            color: var(--vscode-charts-blue, var(--vscode-textLink-foreground));
            padding: 3px 0 4px 10px;
            border-left: 3px solid var(--vscode-charts-blue, var(--vscode-textLink-foreground));
        }
        label {
            display: block;
            margin: 6px 0 2px;
            font-size: 12px;
        }
        input[type="text"], input[type="number"], select, textarea {
            width: 100%;
            box-sizing: border-box;
            background: var(--vscode-input-background);
            color: var(--vscode-input-foreground);
            border: 1px solid var(--vscode-input-border, transparent);
            padding: 3px 5px;
            font-family: var(--vscode-font-family);
            font-size: 12px;
        }
        textarea { min-height: 44px; font-family: var(--vscode-editor-font-family); }
        .row { display: flex; gap: 6px; align-items: end; }
        .row > * { flex: 1; }
        button {
            background: var(--vscode-button-background);
            color: var(--vscode-button-foreground);
            border: none;
            padding: 5px 10px;
            cursor: pointer;
            font-size: 12px;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            line-height: 1.2;
        }
        button:hover { background: var(--vscode-button-hoverBackground); }
        button.secondary {
            background: transparent;
            color: var(--vscode-charts-blue, var(--vscode-textLink-foreground));
            border: 1px solid var(--vscode-charts-blue, var(--vscode-textLink-foreground));
        }
        button.secondary:hover {
            background: rgba(100, 170, 255, 0.1);
        }
        button.primary {
            background: rgba(71, 212, 90, 0.1);
            color: var(--vscode-charts-green, var(--vscode-textLink-foreground));
            border: 1px solid var(--vscode-charts-green, var(--vscode-textLink-foreground));
        }
        button.primary:hover {
            background: rgba(71, 212, 90, 0.2);
        }
        button.link {
            background: transparent;
            color: var(--vscode-textLink-foreground);
            padding: 2px 4px;
            font-size: 11px;
        }
        .hint {
            font-size: 11px;
            color: var(--vscode-descriptionForeground);
            margin-top: 2px;
        }
        .actions {
            display: flex;
            gap: 6px;
            margin-top: 10px;
            padding-top: 8px;
            border-top: 1px solid var(--vscode-panel-border);
        }
        .status {
            font-size: 11px;
            color: var(--vscode-descriptionForeground);
            margin-top: 6px;
            min-height: 14px;
        }
        .cov-row {
            display: grid;
            grid-template-columns: 1fr 1fr 1fr 60px 24px;
            gap: 4px;
            align-items: center;
            margin-top: 4px;
        }
        .cov-row input, .cov-row select { padding: 2px 4px; font-size: 11px; }
        .base-tabs { display: flex; gap: 4px; }
        .base-tabs label {
            flex: 1; padding: 5px 6px; border: 1px solid var(--vscode-panel-border);
            border-radius: 3px;
            cursor: pointer; margin: 0;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            line-height: 1.2;
            transition: background 0.15s, border-color 0.15s;
        }
        .base-tabs label:hover {
            background: var(--vscode-list-hoverBackground);
        }
        .base-tabs label:has(input:checked) {
            border-color: var(--vscode-charts-purple, var(--vscode-textLink-foreground));
            background: rgba(160, 120, 220, 0.08);
        }
        .base-tabs input { display: none; }
        .base-tabs input:checked + span {
            color: var(--vscode-charts-purple, var(--vscode-textLink-foreground));
        }
        .toggle-box {
            display: flex;
            align-items: center;
            justify-content: center;
            width: 100%;
            box-sizing: border-box;
            background: var(--vscode-input-background);
            color: var(--vscode-input-foreground);
            border: 1px solid var(--vscode-input-border, transparent);
            padding: 3px 5px;
            font-family: var(--vscode-font-family);
            font-size: 12px;
            cursor: pointer;
            margin: 0;
            transition: background 0.15s, border-color 0.15s;
        }
        .toggle-box:hover {
            background: var(--vscode-list-hoverBackground);
        }
        .toggle-box input { display: none; }
        .toggle-box .toggle-yes { display: none; }
        .toggle-box:has(input:checked) {
            border-color: var(--vscode-charts-purple, var(--vscode-textLink-foreground));
            background: rgba(160, 120, 220, 0.08);
            color: var(--vscode-charts-purple, var(--vscode-textLink-foreground));
        }
        .toggle-box:has(input:checked) .toggle-no { display: none; }
        .toggle-box:has(input:checked) .toggle-yes { display: inline; }
    </style>
</head>
<body>
    <h3>Base model</h3>
    <div class="base-tabs">
        <label><input type="radio" name="baseKind" value="fromDataset" checked><span>From dataset</span></label>
        <label><input type="radio" name="baseKind" value="fromModel"><span>From model</span></label>
    </div>

    <div id="fromDataset-block">
        <label>Dataset</label>
        <div class="row">
            <input type="text" id="dataset" placeholder="Path to CSV/TSV">
            <button class="secondary" id="browse-dataset" style="flex:0 0 auto;">Browse…</button>
        </div>
        <div class="row">
            <div>
                <label for="administration">Administration</label>
                <select id="administration">
                    <option value="iv">iv</option>
                    <option value="oral" selected>oral</option>
                    <option value="iv+oral">iv+oral</option>
                </select>
            </div>
            <div>
                <label for="datatype">Data type</label>
                <select id="datatype">
                    <option value="nonmem" selected>nonmem</option>
                    <option value="nlmixr">nlmixr</option>
                </select>
            </div>
        </div>
    </div>

    <div id="fromModel-block" style="display:none;">
        <label>Existing model file</label>
        <div class="row">
            <input type="text" id="modelFile" placeholder=".mod / .ctl">
            <button class="secondary" id="browse-model" style="flex:0 0 auto;">Browse…</button>
        </div>
    </div>

    <label for="modelName">Model name</label>
    <input type="text" id="modelName" placeholder="e.g. run1">

    <h3>Structural features</h3>
    <div class="row">
        <div>
            <label for="absorption">Absorption</label>
            <select id="absorption">
                <option value="none">— none —</option>
                <option value="FO" selected>FO</option>
                <option value="ZO">ZO</option>
                <option value="SEQ-ZO-FO">SEQ-ZO-FO</option>
            </select>
        </div>
        <div>
            <label for="elimination">Elimination</label>
            <select id="elimination">
                <option value="FO" selected>FO</option>
                <option value="ZO">ZO</option>
                <option value="MM">MM</option>
                <option value="MIX-FO-MM">MIX-FO-MM</option>
            </select>
        </div>
    </div>
    <div class="row">
        <div>
            <label for="transits">Transit comp.</label>
            <input type="number" id="transits" step="1" min="0" value="0">
        </div>
        <div>
            <label for="peripherals">Peripheral comp.</label>
            <input type="number" id="peripherals" step="1" min="0" value="0">
        </div>
        <div>
            <label for="lagTime">Lag time</label>
            <label class="toggle-box">
                <input type="checkbox" id="lagTime">
                <span class="toggle-no">No</span>
                <span class="toggle-yes">Yes</span>
            </label>
        </div>
    </div>

    <h3>Between-subject variability (IIV)</h3>
    <label>Parameters (comma separated)</label>
    <div class="row">
        <input type="text" id="iivParameters" placeholder="e.g. CL, V, KA">
        <select id="iivType" style="flex:0 0 90px;">
            <option value="exp" selected>exp</option>
            <option value="prop">prop</option>
            <option value="add">add</option>
        </select>
    </div>
    <div class="hint">Leave empty to skip <code>add_iiv()</code>.</div>

    <h3>Residual error</h3>
    <div class="row">
        <div>
            <label for="errorModel">Type</label>
            <select id="errorModel">
                <option value="none">— none —</option>
                <option value="additive">additive</option>
                <option value="proportional" selected>proportional</option>
                <option value="combined">combined</option>
            </select>
        </div>
        <div>
            <label for="dv">DV column (optional)</label>
            <input type="text" id="dv" placeholder="e.g. DV">
        </div>
    </div>

    <h3>Covariate effects</h3>
    <div id="cov-rows"></div>
    <button class="link" id="add-cov">+ Add covariate row</button>
    <div class="hint">Effect examples: <code>lin</code>, <code>pow</code>, <code>exp</code>, <code>cat</code>, <code>piece_lin</code>.</div>

    <h3>Output</h3>
    <div class="row">
        <div>
            <label for="outputFormat">Convert to</label>
            <select id="outputFormat">
                <option value="nonmem" selected>nonmem</option>
                <option value="nlmixr2">nlmixr2</option>
                <option value="none">— skip conversion —</option>
            </select>
        </div>
        <div>
            <label for="outputModelFile">Write model file</label>
            <input type="text" id="outputModelFile" placeholder="e.g. run1.mod">
        </div>
    </div>

    <div class="actions">
        <button class="primary" id="generate">Generate Code</button>
    </div>

    <script>
        const vscode = acquireVsCodeApi();

        const fromDatasetBlock = document.getElementById('fromDataset-block');
        const fromModelBlock = document.getElementById('fromModel-block');
        function refreshBase() {
            const kind = document.querySelector('input[name="baseKind"]:checked').value;
            fromDatasetBlock.style.display = kind === 'fromDataset' ? '' : 'none';
            fromModelBlock.style.display   = kind === 'fromModel'   ? '' : 'none';
        }
        document.querySelectorAll('input[name="baseKind"]').forEach(r =>
            r.addEventListener('change', refreshBase)
        );
        refreshBase();

        const covRows = document.getElementById('cov-rows');
        function addCovRow(prefill) {
            const row = document.createElement('div');
            row.className = 'cov-row';
            row.innerHTML = \`
                <input type="text" placeholder="Parameter (e.g. CL)" class="cov-p">
                <input type="text" placeholder="Covariate (e.g. WT)" class="cov-c">
                <select class="cov-e">
                    <option value="lin">lin</option>
                    <option value="pow">pow</option>
                    <option value="exp">exp</option>
                    <option value="cat">cat</option>
                    <option value="piece_lin">piece_lin</option>
                </select>
                <select class="cov-o">
                    <option value="*">*</option>
                    <option value="+">+</option>
                </select>
                <button class="link cov-del">✕</button>
            \`;
            covRows.appendChild(row);
            row.querySelector('.cov-del').addEventListener('click', () => row.remove());
            if (prefill) {
                row.querySelector('.cov-p').value = prefill.parameter || '';
                row.querySelector('.cov-c').value = prefill.covariate || '';
                row.querySelector('.cov-e').value = prefill.effect || 'lin';
                row.querySelector('.cov-o').value = prefill.operation || '*';
            }
        }
        document.getElementById('add-cov').addEventListener('click', () => addCovRow());

        function collectCovariates() {
            return Array.from(covRows.querySelectorAll('.cov-row')).map(r => ({
                parameter: r.querySelector('.cov-p').value.trim(),
                covariate: r.querySelector('.cov-c').value.trim(),
                effect:    r.querySelector('.cov-e').value,
                operation: r.querySelector('.cov-o').value
            })).filter(x => x.parameter && x.covariate);
        }

        function collect() {
            const str = (id) => document.getElementById(id).value;
            const num = (id) => {
                const raw = document.getElementById(id).value;
                if (raw === '' || raw === null || raw === undefined) { return 0; }
                const n = Number(raw);
                return Number.isFinite(n) ? n : 0;
            };
            const iivRaw = str('iivParameters');
            const iivParams = iivRaw.split(',').map(s => s.trim()).filter(Boolean);
            return {
                baseKind: document.querySelector('input[name="baseKind"]:checked').value,
                dataset: str('dataset'),
                modelFile: str('modelFile'),
                modelName: str('modelName'),
                datatype: str('datatype'),
                administration: str('administration'),
                absorption: str('absorption'),
                transits: num('transits'),
                lagTime: document.getElementById('lagTime').checked,
                elimination: str('elimination'),
                peripherals: num('peripherals'),
                iivParameters: iivParams,
                iivType: str('iivType'),
                errorModel: str('errorModel'),
                dv: str('dv'),
                covariates: collectCovariates(),
                outputFormat: str('outputFormat'),
                outputModelFile: str('outputModelFile')
            };
        }

        document.getElementById('browse-dataset').addEventListener('click', () => {
            vscode.postMessage({ command: 'browseDataset' });
        });
        document.getElementById('browse-model').addEventListener('click', () => {
            vscode.postMessage({ command: 'browseModel' });
        });
        document.getElementById('generate').addEventListener('click', () => {
            vscode.postMessage({ command: 'generate', config: collect() });
        });

        window.addEventListener('message', (event) => {
            const msg = event.data;
            if (msg.command === 'datasetPicked') {
                document.getElementById('dataset').value = msg.path;
            } else if (msg.command === 'modelPicked') {
                document.getElementById('modelFile').value = msg.path;
            }
        });
    </script>
</body>
</html>`;
    }
}
